# Generated by Django 2.1 on 2019-02-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagrepos', '0002_repo_repo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Repo',
        ),
    ]
