# Generated by Django 2.1 on 2019-02-26 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('tagrepos', '0004_repo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repo',
            new_name='Repository',
        ),
    ]
